# **Deep Learning**

Deep learning is a smart subset of machine learning that uses multi-layered artificial neural networks to mimic the human brain and automatically find patterns in massive amounts of data. The main types of deep learning architectures include Convolutional Neural Networks (CNNs), Recurrent Neural Networks (RNNs), and Generative Adversarial Networks (GANs)

# **Tensor**

Tensor is a multi dimensinal array used to store and process data

# **Types of tensorflow**

1. sacalar
2. vector
3. matrix
4. 3D Tensor
5. Higher

# **Tensorflow Workflow**

Collect Dataset -> Preprocess Data -> Convert data into Tensors - > Build neural network -> Train model -> Evaluate model -> Make prdictions

# **Keras**

Keras is a high level API of tensorflow used to build and train deep learning model easily

# **Keras Workflow**

  Import Keras -
  Create Model -
  Add Layyers -
  Compile Model -
  Train Model -
  Evaluate Model -
  Predict.


In [ ]:
from tensorflow import keras

#or

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

# Create an empty neural networks
model = Sequential()

print(model)

#Add layers

model = Sequential()

#Hidden Layer

model.add(Dense(16,activation="relu", input_shape=(4,)))

#Hidden Layer

model.add(Dense(8,activation="relu"))

# output layer
model.add(Dense(8,activation="sigmoid"))

model.summary()


<Sequential name=sequential_2, built=False>


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │            72 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 288 (1.12 KB)

 Trainable params: 288 (1.12 KB)

 Non-trainable params: 0 (0.00 B)

# **Relationship between Tensorflow and Keras**

TensorFlow -> Keras API -> Build Nural Networks -> Train Model -> Predict results

In [ ]:
import tensorflow as tf

# Scalar Tensor (0D)
scalar = tf.constant(10)
print("Scalar:", scalar)

# Vector Tensor (1D)
vector = tf.constant([10, 20, 30])
print("Vector:", vector)

# Matrix Tensor (2D)
matrix = tf.constant([[10, 20, 30], [40, 50, 60]])
print("Matrix:", matrix)

Scalar: tf.Tensor(10, shape=(), dtype=int32)
Vector: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf

a = tf.constant(10)
b = tf.constant(5)

print("Addition:",tf.add(a,b))
print("Subtraction:",tf.subtract(a,b))
print("Multiplication:",tf.multiply(a,b))
print("Division:", tf.divide(a,b))

Addition: tf.Tensor(15, shape=(), dtype=int32)
Subtraction: tf.Tensor(5, shape=(), dtype=int32)
Multiplication: tf.Tensor(50, shape=(), dtype=int32)
Division: tf.Tensor(2.0, shape=(), dtype=float64)


In [ ]:
import tensorflow as tf

matrix1 = tf.constant([[1, 2, 3],[7,8,9]])
matrix2 = tf.constant([[4, 5, 6],[11,12,13]])
print("Matrix:", tf.multiply(matrix1,matrix2))



Matrix: tf.Tensor(
[[  4  10  18]
 [ 77  96 117]], shape=(2, 3), dtype=int32)


# **Building Neural Networks**

Buildong a neural ntwork is the process of creating the structure of an ANN by adding layers,neurons,and activation functions using Tensorflow and Keras

# **Steps to build a Neural networks**

Import Libraries -> Create Sequential Model -> Add Input Layer -> Add Hidden Layers -> Add Output Layer -> Compile Model -> train Model -> Make predictions

# **Componenets of a neural Networks**

1. Input Layer
2. Hodden layer
3. Output Layer

////////////////

1. sequential: It is used to interconnected the layers or neurons
2. Dense: No of neurons
3. sigmoid : for binary classification
4. relu: for convert negative no into 0.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create Neural Network
model = Sequential()

# Input + Hidden layer
model.add(Dense(
    units = 16,
    activation = "relu",
    input_shape = (2,)
))


# Hidden layer
model.add(Dense(
    units = 8,
    activation = "relu"
))
# Output layer
model.add(Dense(
    units = 1,
    activation = "sigmoid"
))

# display Model summary
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 193 (772.00 B)

 Trainable params: 193 (772.00 B)

 Non-trainable params: 0 (0.00 B)

# **Model compilation in Tensorflow & Keras**

Model compilation is the process of configuring a neural network by specifying the optimizer, loss function, and evaluation metrics before training.

Componenets:

**1. Optimizer -**
 An optimizer adjusts the weights of the neural networks to minimize the loss and amprove predictions accuracy

 . adam
 . SGD
 . RMSprop
 . Adagrad

 **2. Loss Function -**
 The loss function calculates the predictions error of the neural network.

 . binary_crosssentropy
 . categoriacl_crosssentropy
 . mean_squared_error(MSE)

 **3. Metrics -**
 Metrics evaluate how well the neural network is performing



In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create Model
model = Sequential()

# Input + Hidden layer
model.add(Dense(units = 16,activation = "relu",input_shape = (2,)))

# Hidden layer
model.add(Dense(units = 8,activation = "relu"))

# Output layer
model.add(Dense(units = 1,activation = "sigmoid"))

# compile Model
model.compile(
    optimizer = "adam",
    loss = "binary_crossentropy",
    metrics = ["accuracy"]
)

# model summary

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 16)             │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 193 (772.00 B)

 Trainable params: 193 (772.00 B)

 Non-trainable params: 0 (0.00 B)

# **Training and Validation in TensorFlow & Keras**

1. training - Training is the process of teaching a neural network using training data so that it can make accurate predictions

2. Validation - Validation is the process of checking

# **Biological vs Artificial Neurons in ANN**

**Biological Neurons**

A biological neuron is the basic functional unit of the human nervous system. It recieves signals from other neurons, processes them , and sends signals to the next neuron

Dendrites
|
Input signals
|
+------------+
| cell body  |
|   (Soma)   |
+------------+
|
Axon
|
Output signal

**Artificial Neurons**

An Artificial Neuron is the mathematical model of a biological neuron used in Artificial Neural Networks (ANNs). It recieves input values, performs calculatins, applies an activation function, and produces an output.

X1
\
X2-----\
        \
X3 -------> Weighted Sum
          /     |
X4 ------/      
           Activation Function
                 |
              Output (Y)

# **Mapping Between Biological and Artficial Neurons**

Biological Neuron Artificial Neuron

1. Dendrites-----------> Inputs (X)
2. Synapse ---------->  Weights (W)
3. Cell Body ---------> Weighted Sum
4. Axon --------------> Output (Y)
5. Brain -------------> Neural network (ANN)

# **Activation Functions**

An activation function determines the output of a neuron by transforming the weighted sum into a meaningful value.

Inputs (X) -> Weighted Sum -> Activation Function -> Output

**Types of Activation Functions**

1. Binary Step:-
 The binary step function gives only two outputs (0, 1) it is mainlu used in perceptron model

 2. Sigmoid Function:-
 It converts any input into a value between o and 1

 3. Tanh Function:-
 The tanh function output values betweeen -1 and +1

 4. ReLU (Rectified Linear Unit):-
  It is used activation function in deep learning

 5. Leaky ReLU:- Leaky Relu is an improved version of Relu. Instead of returning 0 for negative values, it returns a small negative value.

 6. Softmax:- Softmax is used for Multi-Class Classification. It converts outputs into probabilities whose total is 1.


# **Perceptron Model**

A perceptron is the simplest artificial Neural Ntwork (ANN) and is the building block of deep learning. it was introduced by Frank Roseblatt in 1958.

It is mainly used for Binary classification, where the output has only two classes:
1. Yes/No
2. Pass/ Fail
3. Spam/Not spam
4. Survived/ Not Survived

Inputs

X1      X2     X3
 |      |       |
 W1     W2     W3
  \      |     /
   \     |    /
    Weighted Sum
         |
       + Bias (b)
          |
    Activation Function
          |
        Output (0 or 1)

  

In [ ]:
import numpy as np

# Inputs

hours = 8
attendance = 90

# weights

w1 = 0.6
w2 = 0.4

# Bias
bias = -4

# Weighted Sum

z = (hours * w1) + (attendance * w2) + bias

print("Weighted Sum:", z)

# Step Activation Function

if z >= 0:
  print("Prediction: Pass")
else:
  print("Prediction: Fail")


Weighted Sum: 36.8
Prediction: Pass


# **Feed Forward Neural Network (FFNN)**

A feed forward neural network is a neural network ewhere information mobes only from the input layer to the output layer without any backward connections